import os

# Сюди я додав усі нові куки з твоїх логів, включаючи довгий __Secure-YNID
RAW_DATA = """
# Netscape HTTP Cookie File
# http://curl.haxx.se/rfc/cookie_spec.html
# This file was generated by EditThisCookie
# URL: https://www.youtube.com/watch?v=wc2gs8pV9Ug
.youtube.com	FALSE	/	TRUE	1810919112.19605	__Secure-1PAPISID	lFlk-pCBHHSgqVR0/Al2ptOFjuHt2NEnr_
.youtube.com	FALSE	/	TRUE	1810919112.196725	__Secure-1PSID	g.a0008wiMDGUfaXN9c6LDAP94GgR_16CBZb3TjsBbiKZ8KHpcMMaRMZvSHMwpUSlkGP7I3CTcXgACgYKAcYSARASFQHGX2MiV3EAZW_Kx6VUBi2fcB7P7RoVAUF8yKqp2adaPFIV3-mC5duw0_Xj0076
.youtube.com	FALSE	/	TRUE	1809505902.257026	__Secure-1PSIDCC	AKEyXzWoFaadJAIv-vP8ClnRtpZgU79P0yqzqxI_4Arg26nH3Jl5WI15OrEovFOz8NKfEKaM3r8
.youtube.com	FALSE	/	TRUE	1809505902.256411	__Secure-1PSIDTS	sidts-CjQBhkeRdyJ-g55egcZBpLJNf9Wlyz0rRo6cukSAUZImB043jO693xfDmuF29iP31BeVFWKmEAA
.youtube.com	FALSE	/	TRUE	1810919112.196136	__Secure-3PAPISID	lFlk-pCBHHSgqVR0/Al2ptOFjuHt2NEnr_
.youtube.com	FALSE	/	TRUE	1810919112.196821	__Secure-3PSID	g.a0008wiMDGUfaXN9c6LDAP94GgR_16CBZb3TjsBbiKZ8KHpcMMaRVSi7q5VRp3bZG-WaZFm2BQACgYKAWsSARASFQHGX2MiCUvGBXDIvEitIJBdFh7hYRoVAUF8yKrbJYDN5AoObxu0neOCPyfr0076
.youtube.com	FALSE	/	TRUE	1809505902.257175	__Secure-3PSIDCC	AKEyXzUjDWHyMf09iZ2t0T4PCjYkRqsNzNlZ7P8nlRKO24QQ6TgO5dCRSTyiII_XmLa8foPVvw
.youtube.com	FALSE	/	TRUE	1809505902.256685	__Secure-3PSIDTS	sidts-CjQBhkeRdyJ-g55egcZBpLJNf9Wlyz0rRo6cukSAUZImB043jO693xfDmuF29iP31BeVFWKmEAA
.youtube.com	FALSE	/	TRUE	1791177554.133529	__Secure-BUCKET	CLcG
.youtube.com	FALSE	/	TRUE	1793466771.166723	__Secure-YNID	18.YT=SUB21iRZ-p8-a2BkpNJJ2y7dH-NhPDZqTmsjQi-jNUXPmKS5FUY5rC4Pm7TLfUdKc1iw3z9P3OcmBmcm3N-ADFJjw-T6OnfTERyiqcW3jgxxWgjeM_EgHopEFVOOiEt7d2NFvuJ684ssGMuwWKMocEJ9OWBmxXlwD6kTxEcje65zedkiWEu4cmR0ECxZUvLu3Wd3pB3kyjSgnzYiO5YyxmaZtnnLvpTd_u5znzdfKaTjFWxA9n_jLKGs2EYzG3GmBDyxD_1oEwzkTY6onYiyr6i2X-Np_9GZ1dNVmLBT21K-BbMSFpsopW5njZmDzVuWItuD1ZPJIvte4vIZX0dqgg
.youtube.com	FALSE	/	FALSE	1784488182	_gcl_au	1.1.1410033900.1776712182
.youtube.com	FALSE	/	FALSE	1810919112.195777	APISID	HbLvXOy8m2eUzSBw/AZBoMhl-52J43qfWI
.youtube.com	FALSE	/	FALSE	1810919112.195353	HSID	ADzdV_XTR06ZkWxfI
.youtube.com	FALSE	/	TRUE	1808311468.693482	LOGIN_INFO	AFmmF2swRgIhAKdqcEcRHjvP8dLV-yHAVYYkMtMQnQ3o0H6--WJb0mhdAiEAq2wGOKlrJlIDAN0EyX9uGDHkQMMXzHdfGnL7whEA7oI:QUQ3MjNmenFiQnRoTHF1dVJ5TW5EUVJpNlJZQkdSYS1MbnpHWVFrN05HYVBCWmRKR1ZWdXc1eEd3Wmh1YXZIWnhIVm1jTGk4MXN0Ujhja3lteUE5LTZ0VDNqZlF5dG9RSzlubG5TZlFvOFE3TkNlRWctOEdINFFWRHFIM3MyaUFXVTVfMUZPYWpHNU55eHdTVlEtN1dpREE3UVFuUnFQNVRB
.youtube.com	FALSE	/	TRUE	1812525758.338885	PREF	f4=4000000&f6=40000000&tz=Europe.Kiev&f5=30000&f7=150&repeat=NONE&gl=US
.youtube.com	FALSE	/	TRUE	1810919112.195955	SAPISID	lFlk-pCBHHSgqVR0/Al2ptOFjuHt2NEnr_
.youtube.com	FALSE	/	FALSE	1810919112.196624	SID	g.a0008wiMDGUfaXN9c6LDAP94GgR_16CBZb3TjsBbiKZ8KHpcMMaRWPPZaFEwV9z4HNAONGy3fAACgYKAacSARASFQHGX2MiC0Y9HJ8gu-xJxMeLEzTbthoVAUF8yKqTkKVCpBoDHFKCQ-DNObOf0076
.youtube.com	FALSE	/	FALSE	1809505902.256868	SIDCC	AKEyXzUj3n2Y9kCRxvkqEilNwcQSiiRG_ueskcvbJJmndq9fV8svkm2JjAqqgyogQPw505B51Q
.youtube.com	FALSE	/	TRUE	1810919112.195619	SSID	A_ciKxR_dMkv5c_d1
.youtube.com	FALSE	/	TRUE	1793515711.535062	VISITOR_INFO1_LIVE	P8f2iYwVWI0
.youtube.com	FALSE	/	TRUE	1793515711.535414	VISITOR_PRIVACY_METADATA	CgJVQRIEGgAgag%3D%3D
.youtube.com	FALSE	/	FALSE		wide	0
.youtube.com	FALSE	/	TRUE		YSC	jSFE7x7Ctuc
"""

def fix_and_save():
    file_path = 'cookies.txt'
    with open(file_path, 'w', encoding='utf-8') as f:
        # Додаємо стандартний заголовок, який вимагає YouTube завантажувач
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# http://curl.haxx.se/rfc/cookie_spec.html\n\n")
        
        for line in RAW_DATA.strip().split('\n'):
            line = line.strip()
            if not line: continue
            
            # split() без аргументів розділяє рядок по будь-якій кількості пробілів або табуляцій
            parts = line.split()
            
            # Якщо частин 7 або більше (буває, що значення кука містить пробіли всередині)
            if len(parts) >= 7:
                # Збираємо перші 6 колонок і додаємо все інше як 7-му колонку (значення кука)
                domain, flag, path, secure, expiry, name = parts[:6]
                value = " ".join(parts[6:])
                
                # Склеюємо їх справжньою табуляцією \t
                fixed_line = f"{domain}\t{flag}\t{path}\t{secure}\t{expiry}\t{name}\t{value}"
                f.write(fixed_line + "\n")
            
            # Спеціальна обробка для коротких куків як "wide 0" або "YSC"
            elif len(parts) == 6:
                fixed_line = "\t".join(parts) + "\t"
                f.write(fixed_line + "\n")

if __name__ == "__main__":
    fix_and_save()
    print("✅ cookies.txt успішно оновлено!")
